# Copyright 2021 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# On push to master only: run proofs and deploy manifest update.

name: Proofs

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - manifest-update

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: seL4/ci-actions/repo-checkout@master
      with:
        manifest_repo: verification-manifest
        manifest: devel.xml

  proofs:
    name: Proof
    needs: code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, RISCV64, X64]
    # test only most recent push:
    concurrency: l4v-regression-${{ github.ref }}-${{ strategy.job-index }}
    steps:
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@master
      with:
        L4V_ARCH: ${{ matrix.arch }}
        xml: ${{ needs.code.outputs.xml }}
        session: '-v'  # non-empty argument to `./run-tests` to not exclude AutoCorresSEL4
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.arch }}
        path: logs.tar.xz

  deploy:
    name: Deploy manifest
    runs-on: ubuntu-latest
    needs: [code, proofs]
    steps:
    - uses: seL4/ci-actions/l4v-deploy@master
      with:
        xml: ${{ needs.code.outputs.xml }}
      env:
        GH_SSH: ${{ secrets.CI_SSH }}
